### ISSUE TITLE
cannot load .bag file

### ISSUE THREAD

**Issue by CAKGOD** [rsasaki0109/graphslam_ros2#18]
**Required Info:**

- Operating System:
  - ubuntu 20.04
- ROS2 Version:
  - ROS2 foxy

#### Steps to reproduce issue
(1) I build this framework following the[ tutorial](https://github.com/rsasaki0109/lidarslam_ros2#requirement-to-build) in the README.md.
(2) I tried running the [demo](https://github.com/rsasaki0109/lidarslam_ros2#trial-environment) and the problem occured.

#### Problem Description
The input [dataset ](https://github.com/rsasaki0109/lidarslam_ros2#trial-environment)provided by the demo is in the .bag file format, but ros2 only provides access to the .sqlite3 file format. Even if the rosbag2 plugin is installed, the .sqlite file still cannot be read. Framework testing cannot continue.
I am very interested in how you read the .bag file in ros2. Can you provide the system version and ros version, or other solutions? Thanks~

**Comment by rsasaki0109** [comment]
The data in the demo was recorded in ros1.
To play a rosbag of ros1 on ros2, you need to install not only ros2 but also ros1.
For ubuntu 20.04, the ros1 you are installing is ros noetic.

Next, you need to install not only rosbag2 but also rosbag2_bag_v2.
https://github.com/ros2/rosbag2_bag_v2


```
sudo apt install -y ros-foxy-rosbag2-bag-v2-plugins
```
See README.md in rosbag2_bag_v2 for details.

**Comment by CAKGOD** [comment]
@rsasaki0109 Thank you very much for your help. I finally solved the problem. Both ros1 and ros2 need to be installed. In addition, the ROS 1 installation must be sourced before sourcing the ROS 2 installation to make the plugin work. The $ros2 bag info -s rosbag_v2 <path_to_bagfile> and the $ros2 bag play -s rosbag_v2 <path_to_bagfile> can be used. But the $ros2 bag record -s rosbag_v2 <topic name> does not work. Thanks again~

**Comment by vico1999-ros** [comment]
Is there any bag can be played on ros2 directly.  both versions of ROS installed on same computer is seem not wise.  finded another data source is more easier

**Comment by rsasaki0109** [comment]
@vico1999-ros 
I don't have a 3D LiDAR, so I can't prepare a ROS 2 rosbag on my own for sample.
You can use [rosbags](https://pypi.org/project/rosbags/) to convert ROS1 rosbags to ROS2 rosbags without installing ROS1. I will update the readme.md later.

**Comment by Er-Ding** [comment]
After I convert .rosbag to .db3 format file and then run the program, I found that the topic /velodyne_points always has message lost problem.How can I solve this problem?
Ubuntu version: 24.04
ROS version: Jazzy

**Comment by rsasaki0109** [comment]
You should ask the creator of rosbags about that.
https://gitlab.com/ternaris/rosbags

**Comment by rsasaki0109** [comment]
How does the message look when it is converted?
 If there are no error outputs, it might be better to ask the author of rosbags.

**Comment by Er-Ding** [comment]
When I converted it, the information like fig1.Although the "bag size" showed 0B, but when I check this file's propertise,it's 2.4G
When I play this data and run "ros2 topic echo /velodyne_points ",the result like fig2


fig1:
fig2:








朱军
***@***.***







                       
Original Email
                       
                     

From:"Ryohei Sasaki"< ***@***.*** &gt;;

Sent Time:2024/7/9 17:09

To:"rsasaki0109/lidarslam_ros2"< ***@***.*** &gt;;

Cc recipient:"Er-Ding"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

Subject:Re: [rsasaki0109/lidarslam_ros2] cannot load .bag file (#18)




 
How does the message look when it is converted?

**Comment by rsasaki0109** [comment]
The image is not displayed.

**Comment by Er-Ding** [comment]
> The image is not displayed.
fig1
![22](https://github.com/rsasaki0109/lidarslam_ros2/assets/114910903/76eabd5e-ae1b-48a8-b0b7-74713785843e)
fig2:
![11](https://github.com/rsasaki0109/lidarslam_ros2/assets/114910903/76d0f0ed-75a9-4b88-92ce-d0125456fe0b)

**Comment by rsasaki0109** [comment]
This is an issue I've never seen before. It might be specific to ROS2 Jazzy.

**Comment by rsasaki0109** [comment]
The bag size is 0B, so it seems like the conversion didn't go well. It might be worth trying to convert it again.
