### ISSUE TITLE
__init__() missing 1 required keyword-only argument: 'node_executable'

### ISSUE THREAD

**Issue by CAKGOD** [rsasaki0109/graphslam_ros2#19]
Excuse me. I build the lidarslam_ros2 done. A problem occured when i run the command $ ros2 launch lidarslam lidarslam.launch.py. The information is as followed.

[ERROR] [launch]: Caught exception in launch (see debug for traceback): Caught exception when trying to load file of format [py]: __init__() missing 1 required keyword-only argument: 'node_executable'

System: ubuntu 18.04
ros version: ros1 melodic + ros2 eloquent

How can i solve this problem? Thank u~

**Comment by rsasaki0109** [comment]
Perhaps changing the "executable" part of the lidarslam.launch.py file to "node_executable" will fix the problem?
From eloquent to foxy,  "node_executable" has been renamed to "executable" and "node_executable" is now deprecated in foxy.

**Comment by CAKGOD** [comment]
thank u ~  i will make a try.

**Comment by CAKGOD** [comment]
It works for me. Thanks! And i will close this issue.
