### ISSUE TITLE
Thanks for sharing. I read your code carefully and found that you use submap.

### ISSUE THREAD

**Issue by hunkyu** [rsasaki0109/graphslam_ros2#22]
Thanks for sharing. I read your code carefully and found that you use submap. This idea is very good. Unfortunately, the front-end and back-end are not completely decoupled. I don't know why? Can it be improved further? Using cartographer's submap idea

**Comment by rsasaki0109** [comment]
Thanks for the good idea. You're right. I would like to improve this package. But I'm too busy right now to do it right away.

**Comment by hunkyu** [comment]
I read the lio-sam version you changed and found that there is a problem with the compilation? I asked you a question, no reply

**Comment by rsasaki0109** [comment]
I responded to that.
