### ISSUE TITLE
ScanMatcher PointCloud Error. Failed to build.

### ISSUE THREAD

**Issue by christophTUM** [rsasaki0109/graphslam_ros2#26]
Hello,
i want to build the package lidarslam_ros2 on Ubuntu 20.04 (Focal Fossa) with ndt_omp_ros2 and g2o installed but i get the following error:

`/home/christoph/IAC/mod_map_loc/LiDAR_SLAM/lidarslam_test_build/lidarslam_ros2/src/scanmatcher/src/scanmatcher_component.cpp:488:32: error: no matching function for call to ‘rclcpp::Publisher<sensor_msgs::msg::PointCloud2_<std::allocator<void> > >::publish(sensor_msgs::msg::PointCloud2_<std::allocator<void> >::Ptr&)’
  488 |   map_pub_->publish(map_msg_ptr);`

I am using PCL 1.10 because of Ubuntu 20.04.

**Comment by rsasaki0109** [comment]
I see your error, you're probably using a package from the ros2-dashing branch, please use a package from the ros2-foxy branch.


ros2 dashing
https://github.com/rsasaki0109/lidarslam_ros2/blob/dashing/scanmatcher/src/scanmatcher_component.cpp#L488
ros2 foxy
https://github.com/rsasaki0109/lidarslam_ros2/blob/foxy/scanmatcher/src/scanmatcher_component.cpp#L488

**Comment by rsasaki0109** [comment]
Since there seems to be no response, I will close this isuue. If you have any more problems, please open it again.
