### ISSUE TITLE
Question for providing odometry

### ISSUE THREAD

**Issue by oskarmue** [rsasaki0109/graphslam_ros2#45]
Lidarslam_ros2 is working great for us, thank you for that!
But when moving outside, there are moments, when lidarslam looses its track and especially when returning to the same point the build map is wrong. (as in picture below)
Therefore, we wanted to add odometry. When doing that, is lidarslam then relying on the provided odometry for 100% or is it just complementary
![Screenshot from 2022-08-08 16-04-09](https://user-images.githubusercontent.com/73947915/184332103-cdc9b4a3-cf91-437d-8236-3561d55ce8d1.png)
?

**Comment by rsasaki0109** [comment]
Adding odometry will cause the initial position for scan matching to use the value estimated by odometry.
This improves the accuracy of scan matching and reduces the likelihood of estimation failure.
