### ISSUE TITLE
Editting PCL

### ISSUE THREAD

**Issue by SyahirMuzni** [rsasaki0109/graphslam_ros2#50]
Hi! 
I just want to ask if I can edit or remove unwanted data from the point cloud data. Are there any tools for that?

**Comment by rsasaki0109** [comment]
If you want to edit a point cloud, you can use [PCL](https://github.com/PointCloudLibrary/pcl).

**Comment by rsasaki0109** [comment]
This is a place to report lidarslam_ros2 issues, not a question place about pointcloud, so please be careful next time.
