### ISSUE TITLE
Map produced not aligned on loop road

### ISSUE THREAD

**Issue by SyahirMuzni** [rsasaki0109/graphslam_ros2#51]
Hi!

I have successfully gotten the map data using the lidarslam. But, there is an issue, I noticed that the map is not aligned when I tried to record it on a loop road (you may see the line in the red circle is not aligned). But when I record it on a non-looping road, it works just fine. How can I resolve this issue? 

Thank you.

![not aligned](https://user-images.githubusercontent.com/94072577/190948344-b509b452-ac5b-4ad2-966b-179adf424566.png)

**Comment by rsasaki0109** [comment]
Is it possible to have your rosbag provided?

**Comment by rsasaki0109** [comment]
I would appreciate information on the type of lidar you used and the yaml file.

Also, how many meters are there from the loop start to the loop end?
With LiDAR only, sometimes it is difficult to close a loop over a long distance, and you may want to use Wheel Odometry.
If you do not have Wheel Odometry, I recommend using the following package, which also requires IMU.
https://github.com/rsasaki0109/li_slam_ros2

**Comment by SyahirMuzni** [comment]
Here is the link of the ros2 bag and yaml file as you requested.
[https://drive.google.com/file/d/1727BwiDbq9OzKh88HWXv_bE_lJSz86sT/view?usp=sharing](url)
[https://drive.google.com/file/d/1BnLPt1LPNYim5uqHsOd4dShrx96x4_Fo/view?usp=sharing](url)

For your information, I am using Velodyne VLP-16 and the start and end of the loop is at the same point.

Also, are you suggesting me that I have to use the lio_bigloop.launch.py if I want to record a loop road?

**Comment by rsasaki0109** [comment]
~The url you provided does not seem to be appropriate; clicking on the url will take me to the following~
Oops, I copied and pasted and it worked.

~https://github.com/rsasaki0109/lidarslam_ros2/issues/url~

lio_bigloop.launch.py makes it easier to close loops over longer distances than this package
But first I will check to see if this package can also close the loop with your data, so please wait a bit.

**Comment by rsasaki0109** [comment]
I have looked at the data and the distances are long enough to be acceptable for this package.
I think there is a bug in the loop closure, so please wait a little while until it is addressed.

**Comment by rsasaki0109** [comment]
The bug has been fixed in the following PR.

before
![image](https://user-images.githubusercontent.com/18298605/191224072-62715d38-bfa3-471f-b06a-e8e3967e7296.png)
after
![image](https://user-images.githubusercontent.com/18298605/191221383-6bf9e06a-a6d5-42bd-8f9d-f5cf2a77b461.png)
PR
https://github.com/rsasaki0109/lidarslam_ros2/pull/52

**Comment by SyahirMuzni** [comment]
Great! I tried to record two loop maps. It worked!
