### ISSUE TITLE
ros2 version of lio-sam

### ISSUE THREAD

**Issue by lucianzhong** [rsasaki0109/graphslam_ros2#59]
Hi:
Thanks for the work of lidarslam_ros2.
 Have you successfully run the ros2 version of lio-sam, and which rosbag to use? And how to set the yaml file?

Thanks

**Comment by rsasaki0109** [comment]
I have never run the ros2 version of lio-sam.

Please open an issue about lio-sam here.
https://github.com/TixiaoShan/LIO-SAM

**Comment by lucianzhong** [comment]
I do have opened an issue in https://github.com/TixiaoShan/LIO-SAM.   Unfortunately, no one answer  this issue https://github.com/TixiaoShan/LIO-SAM/issues/387

**Comment by rsasaki0109** [comment]
That is not a good reason to ask questions about lio-sam in this repository.
