### ISSUE TITLE
PCL Version

### ISSUE THREAD

**Issue by szyasin** [rsasaki0109/graphslam_ros2#63]
Hello, after I successfully completed the requirements to build steps, I encountered the fault that is below in the last step which is for using to build. What should I do?

`colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release
`

```

user@ubuntu:~/ros2_ws$ colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release

Starting >>> lidarslam_msgs
Starting >>> ndt_omp_ros2
Finished <<< lidarslam_msgs [0.72s]                                                             
--- stderr: ndt_omp_ros2                         
CMake Error at CMakeLists.txt:23 (find_package):
  Could not find a configuration file for package "PCL" that is compatible
  with requested version "1.12".

  The following configuration files were considered but not accepted:

    /usr/share/pcl-1.8/PCLConfig.cmake, version: 1.8.0



make: *** [Makefile:370: cmake_check_build_system] Error 1
---
Failed   <<< ndt_omp_ros2 [0.96s, exited with code 2]

Summary: 1 package finished [1.23s]
  1 package failed: ndt_omp_ros2
  1 package had stderr output: ndt_omp_ros2
  3 packages not processed

```

**Comment by rsasaki0109** [comment]
What is your ros2 vesion? Maybe it is old.
Depending on the version of ros2 (dashing/foxy/humble), you will need to switch branches for this package.

**Comment by szyasin** [comment]
It's 22.04 LTS Ubuntu and I installed the latest version of foxy from ros.org/en/foxy 2 days ago. Should I try with other distributions of ros2 ?
![image](https://user-images.githubusercontent.com/101212641/218302624-bfe21c98-2d44-476b-b278-fae196510e49.png)

**Comment by rsasaki0109** [comment]
For foxy, it is the following branch.
https://github.com/rsasaki0109/lidarslam_ros2/tree/foxy

**Comment by rsasaki0109** [comment]
I'm closing this issue since we haven't seen any recent activity. If the problem comes up again, feel free to open a new issue at any time.
