### ISSUE TITLE
Localization in previously built map

### ISSUE THREAD

**Issue by mrmara** [rsasaki0109/graphslam_ros2#66]
Hi, I was able to build a map but I was wondering if your package makes it possible to localize in the saved map.

Thank you

**Comment by rsasaki0109** [comment]
That is not possible with this package.
For example, use the following


https://github.com/rsasaki0109/pcl_localization_ros2
https://github.com/autowarefoundation/autoware.universe/tree/main/localization

**Comment by rsasaki0109** [comment]
I will close this issue as the problem seems to have been resolved.
