### ISSUE TITLE
scan_period parameter

### ISSUE THREAD

**Issue by yvzksgl** [rsasaki0109/graphslam_ros2#68]
Hello,

README says "scan period of input cloud[sec](If you want to compound imu, you need to change this parameter.)". I couldn't understand how to change this parameter, should it be the same as imu message's period or what should it be? 

Thank you.

**Comment by rsasaki0109** [comment]
The time interval between LiDAR scan messages.

**Comment by yvzksgl** [comment]
I see, I have one more question if it doesn't bother you. I am creating imu messages from GNSS data which has 200hz frequency. Should I synchronize it with pointcloud. I mean should I just use imu data that have same timestamp with pointcloud. The reason why I'm asking this I understood from code there is no problem with using 200hz data but, it's not using imu data in that case.

**Comment by rsasaki0109** [comment]
It would be better to synchronize them. The IMU fusion was modeled after LEGO-LOAM, so you may find some hints in that repository.

**Comment by rsasaki0109** [comment]
If you're incorporating an IMU, I think it would be better to fuse it with the vehicle speed as odometry or use li_slam_ros2 instead of this package.

https://github.com/rsasaki0109/li_slam_ros2

**Comment by yvzksgl** [comment]
Thanks for your response i will try it.
