### ISSUE TITLE
Scan_Matcher "odom"-Frame Error

### ISSUE THREAD

**Issue by LuSchnitt** [rsasaki0109/graphslam_ros2#79]
Hello, 

the installation of the package went very smoothly and without problems.
But when i try to test it, with my ros2-bag, i got the following error only after i started to publish the data from the bag:

![scanmatcher_error](https://github.com/rsasaki0109/lidarslam_ros2/assets/117588820/590adc05-32ef-4985-a82c-431ea638ab83)

System: ubuntu 20.04
Ros: Foxy
Arm64 Architecture

I was working with the scanmatcher a few months ago and i didnt get any error like this with the tested ros_bags. 

Do you know how i can get solve this problem?

If you need more information just ask.

Best 

Lukas

**Comment by rsasaki0109** [comment]
Is the scanmatcher.use_odom in your yaml set to true? If you don't have odometry as a sensor input, you need to set use_odom to false.

**Comment by LuSchnitt** [comment]
Thanks, that solved the problem!

Best Lukas
