### ISSUE TITLE
Wrong transformation when an odometry is used 

### ISSUE THREAD

**Issue by delipl** [rsasaki0109/graphslam_ros2#87]
The current transform publisher works wrong when an odometry is used.
[Screencast from 22.04.2024 21:50:52.webm](https://github.com/rsasaki0109/lidarslam_ros2/assets/33808634/11067a5d-08e2-445d-9449-445bb42c5088)

The proper tf tree should look:
base_link -> odom -> map
but current implementation provides:
base_link -> odom
base_link -> map

The proposition of solution https://github.com/rsasaki0109/lidarslam_ros2/pull/86

**Comment by rsasaki0109** [comment]
The related pull request has been merged, so I am closing this issue.
